### ISSUE TITLE
PIM / DAM : SVG Upload Error but an assets without category link gets created

### ISSUE THREAD

**Issue by rmoecklideveloper** [atrocore/atrocore#1222]
PIM 1.11.26 / atrocore 1.9.15
Upload an file.svg (Version 1.1) creates an error. After searching for it it got somehow created, shows up quickly than disappears.
Looking into the database, asset is there, imagemagick can't process it I guess, No Entry in asset_category_asset table.
Manually add the row in asset_category_asset talbe, all good, despite there is no preview.

In my opinion, if asset can't be processed for preview, add the asset anyway totally
or totally deny it, but don't do it half ;-) 

`[2024-04-16T11:17:59.865991+00:00] Log.ERROR: API [POST]:/api/v1/:controller, Params:Array (     [controller] => Asset ) , InputData: {"type":["Icon"],"libraryName":"Default Library","libraryId":"1","fileId":"y661e5e4b11913eb8","name":"snapfix.svg","isActive":true,"private":false,"parentsIds":[],"parentsNames":{},"description":null,"descriptionFrCh":null,"descriptionItCh":null,"tags":[],"tagsFrCh":[],"tagsItCh":[],"afterSaveMessage":"","ProductAsset__scope":"Global","ProductAsset__channel":"","fileName":"snapfix.svg","_prev":{"libraryName":"Default Library","libraryId":"1","isActive":true,"private":false,"afterSaveMessage":"","ProductAsset__scope":"Global","ProductAsset__channel":""},"_silentMode":true} - unable to open file `/tmp/magick-kNCdwYGBnHI7CcQru5cHmpF-wxWkW2ec': No such file or directory @ error/constitute.c/ReadImage/614 [] []
[2024-04-16T11:17:59.867847+00:00] Log.ERROR: Display Error: unable to open file `/tmp/magick-kNCdwYGBnHI7CcQru5cHmpF-wxWkW2ec': No such file or directory @ error/constitute.c/ReadImage/614, Code: 430 URL: /api/v1/Asset [] []`
![paket](https://github.com/atrocore/atrocore/assets/54440956/169fbd4d-4bbc-4669-8cd2-6ff50aa82e20)

**Comment by AnnZast** [comment]
Hello
Please, update your environment to Core 1.10.0. We made deep refactoring of the mechanisms for working with files. Entities Asset, Attachment, AssetType, AssetCategory, Library have been removed. These API endpoint were removed too. Entities File, FileType, Folder, Storage have been added instead. Data was migrated into new entities. Also relationship entities such as ProductAsset has been changed to ProductFile (CategoryAsset -> CategoryFile, etc).

Check if your issue is still relevant. There is no preview for svg files yet, but they can be stored in the same way as other file types.

**Comment by rmoecklideveloper** [comment]
Ok with the new Version, now 1.13 there is no Error displaying, but also now no preview. Would be nice to see in future an option to configure preview of files for assetTypes, just basic imagemagick ghostscript commands, like:
![Bildschirmfoto 2024-09-11 um 08 27 09](https://github.com/user-attachments/assets/711310d8-208e-40c3-9c6e-b4e7f74251c6)
