### ISSUE TITLE
Error handling on Import Feeds does not report issues

### ISSUE THREAD

**Issue by paultvis** [atrocore/atrocore#1292]
When running an import feed using an import file, the import runs and reports successful if the import file does not match the configuration. All lines will fail but the error given does not indicate that the column could not be found.

Expected behaviour on this should be (I am guessing) that if the file being uploaded and imported does not match the configuration, the import job should report a failure and give a file mismatch as the reason.

**Comment by rratsun** [comment]
File is not required field for Import Feed. We need file only for filling Source Fields. Import file can be CSV, XLSX, JSON, XML. Not nessesory that column should always be exists on every import job and it is ok. Only fields marked as Identifier are required because Import will try to find record by this field. When you will run import and system will not find this field you will get an error.
