### ISSUE TITLE
Update Atrocore to 10.31 and folder custom

### ISSUE THREAD

**Issue by Vladzimir** [atrocore/atrocore#1294]
app/Atro/Migrations/V1Dot10Dot31.php
`  self::removeDir('custom');
`
This update remove my twig function!!!
custom/Espo/Custom/TwigFunction

**Comment by rratsun** [comment]
Hello. We've removed the ability to write any custom code unless you do it in your own module. How to develop your own module you can read here https://help.atrocore.com/developer-guide/own-modules.

More details on our decision. Our system is a quite complex thing. We have a lot of modules that can change the behaviour of the system. We also change the system from version to version. That's why the system and the modules have dependencies between each other. Dependencies allow us to control the stability of the system. From this point of view we can't keep ability to write custom code in custom dir because the main logic of dependencies we be broken. Let's take a closer look at your example. What if in the next version we will change Interface for all twig function? System will be updated, but your code will not work. That' why you have to develop your own module and set correct dependency to core and other modules if you want.
