### ISSUE TITLE
File Permissions with new uploads

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrocore#41]
After updating to atrocore 1.1.* (from 1.0.* from beginning of 2021), I noticed that stored files got moved from the /data/* folder to /upload/* - somehow I had some issues and I had to manually move the files, that worked. But now every new file/image I upload has issues. No thumbnails are being created and download is not possible. It looks like the files are ending up on the server with file permission `0600`.
After I change the permission manually I can access the original file in /upload/file/* but I guess thumbnails are created while uploading, so they are still missing.

Any idea how to fix this or is that work in progress?

**Comment by rratsun** [comment]
After updating all files (by default) should be on 'upload/files/', so make sure that owner of this direcory is www-data. I supose that you update your system manualy (from CLI) by another user that's why you have such problems. 
As for thumbnails, all files (by default) should be on 'upload/thumbnails/'. The thumbnails creating on file uploading or when someone calling the thumbnail, so if you solve the problems with permissions the thumbnails should created. And, please, pey attiontion on browser cache.
