### ISSUE TITLE
Interface language translate & search api

### ISSUE THREAD

**Issue by quangbahoa** [atrocore/atrocore#748]
Hello,

I'v read the docs but cannot find how to translate interface language to my language. Also, I cannot find search api from api docs.

Regards,

**Comment by exeqtwasnotfree** [comment]
Be careful if you do this to a system full of data, If you delete a language, you will delete all translations to this language.

If i recall correct I deleted unused languages and added my languages under Admin -> settings -> interface language
When under admin -> language I have only my second language (English), (We run the system in your own language as default)
After what you have to edit the Layouts to show fields in the languages you have selected.
For example Product -> Details, you may want product name for every language because it is per default required.

And to be able to translate the system you have to add your languages fields to the layout translations -> details

And if you visit your site, and add /apidocs after the adress (<atrocore-server-adress>/apidocs/), you get the api-manual.
Hope this helps along.

**Comment by atrolex** [comment]
as for UI translation refer to this:
https://github.com/atrocore/atrocore/discussions/286

**Comment by quangbahoa** [comment]
Thanks @exeqtwasnotfree  and @atrolex

**Comment by atrolex** [comment]
we plan to onboard an external system for translations soon... but till than you can "push" us for translations.
